package main

import (
	"bytes"
	"fmt"
	"math"
	"strings"

	"github.com/go-pdf/fpdf"
)

func generateInvoicePDF(inv Invoice) ([]byte, error) {
	pdf := fpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 20)

	// Margins: left 15mm, top 15mm, right 15mm
	pdf.SetMargins(15, 15, 15)

	pdf.AddPage()

	_ = pdf.GetStringWidth
	pageW, _ := pdf.GetPageSize()
	usableW := pageW - 15 - 15 // 180mm on A4
	colQty := 20.0
	colPrice := 28.0
	colAmt := 30.0
	colDesc := usableW - colQty - colPrice - colAmt

	var (
		headerColor = []int{37, 99, 235} // blue-600
		darkColor   = []int{31, 41, 55}  // gray-800
		grayColor   = []int{107, 114, 128}
		lightBg     = []int{249, 250, 251}
		whiteBg     = []int{255, 255, 255}
	)

	// ── Header ──────────────────────────────────────────────────────────
	pdf.SetFillColor(headerColor[0], headerColor[1], headerColor[2])
	pdf.Rect(0, 0, pageW, 42, "F")

	pdf.SetFont("Helvetica", "B", 28)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetY(12)
	pdf.CellFormat(0, 12, "INVOICE", "", 1, "L", false, 0, "")

	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(220, 220, 255)
	pdf.CellFormat(0, 6, fmt.Sprintf("Invoice #%s", inv.ID), "", 1, "L", false, 0, "")

	// Company name on the right
	pdf.SetFont("Helvetica", "B", 12)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetXY(pageW-80, 12)
	pdf.CellFormat(65, 10, "Invoice Maker", "", 0, "R", false, 0, "")

	pdf.Ln(16)

	// ── Bill To ─────────────────────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 11)
	pdf.SetTextColor(darkColor[0], darkColor[1], darkColor[2])
	pdf.Cell(20, 6, "Bill To:")
	pdf.Ln(8)

	pdf.SetFont("Helvetica", "", 12)
	pdf.CellFormat(0, 6, inv.ClientName, "", 1, "L", false, 0, "")

	pdf.SetFont("Helvetica", "", 10)
	pdf.SetTextColor(grayColor[0], grayColor[1], grayColor[2])
	pdf.CellFormat(0, 5, fmt.Sprintf("Date: %s", inv.Date), "", 1, "L", false, 0, "")
	pdf.Ln(6)

	// ── Items Table ─────────────────────────────────────────────────────
	// Table header
	pdf.SetFillColor(37, 99, 235)
	pdf.SetTextColor(255, 255, 255)
	pdf.SetFont("Helvetica", "B", 9)

	yBefore := pdf.GetY()
	pdf.Rect(15, pdf.GetY(), usableW, 8, "F")
	pdf.SetXY(15, yBefore)
	pdf.CellFormat(colDesc, 8, "  Description", "", 0, "L", false, 0, "")
	pdf.CellFormat(colQty, 8, "Qty", "", 0, "C", false, 0, "")
	pdf.CellFormat(colPrice, 8, "Price", "", 0, "C", false, 0, "")
	pdf.CellFormat(colAmt, 8, "Amount", "", 0, "R", false, 0, "")
	pdf.Ln(8)

	// Table rows
	var subtotal float64
	for i, item := range inv.Items {
		bg := lightBg
		if i%2 == 0 {
			bg = whiteBg
		}
		pdf.SetFillColor(bg[0], bg[1], bg[2])

		y := pdf.GetY()
		pdf.Rect(15, y, usableW, 7, "F")

		pdf.SetTextColor(darkColor[0], darkColor[1], darkColor[2])
		pdf.SetFont("Helvetica", "", 10)
		amount := math.Round(item.Qty*item.Price*100) / 100
		subtotal += amount

		pdf.SetXY(15, y+1.5)
		pdf.CellFormat(colDesc, 5, "  "+truncate(item.Description, 50), "", 0, "L", false, 0, "")
		pdf.CellFormat(colQty, 5, fmt.Sprintf("%.0f", item.Qty), "", 0, "C", false, 0, "")
		pdf.CellFormat(colPrice, 5, formatMoney(item.Price), "", 0, "C", false, 0, "")
		pdf.CellFormat(colAmt, 5, formatMoney(amount), "", 0, "R", false, 0, "")
		pdf.Ln(7)
	}

	// Bottom table border
	pdf.SetDrawColor(37, 99, 235)
	pdf.SetLineWidth(0.3)
	tableBottom := pdf.GetY()
	pdf.Line(15, tableBottom, 15+usableW, tableBottom)
	pdf.Ln(4)

	// ── Totals ───────────────────────────────────────────────────────────
	taxAmount := math.Round(subtotal*inv.TaxRate) / 100
	total := subtotal + taxAmount

	alignX := 15 + usableW - colAmt
	labelW := usableW - colAmt - 30

	totalRow := func(label, value string, bold bool) {
		if bold {
			pdf.SetFont("Helvetica", "B", 11)
			pdf.SetTextColor(37, 99, 235)
		} else {
			pdf.SetFont("Helvetica", "", 10)
			pdf.SetTextColor(darkColor[0], darkColor[1], darkColor[2])
		}
		pdf.SetX(alignX - labelW)
		pdf.CellFormat(labelW, 6, label, "", 0, "R", false, 0, "")
		pdf.SetX(alignX)
		pdf.CellFormat(colAmt, 6, value, "", 1, "R", false, 0, "")
		pdf.Ln(2)
	}

	pdf.Ln(2)
	totalRow("Subtotal:", formatMoney(subtotal), false)
	totalRow(fmt.Sprintf("Tax (%.1f%%):", inv.TaxRate), formatMoney(taxAmount), false)

	pdf.SetDrawColor(200, 200, 200)
	pdf.SetLineWidth(0.2)
	divY := pdf.GetY()
	pdf.Line(alignX-labelW, divY, alignX+colAmt, divY)
	pdf.Ln(3)

	totalRow("Total:", formatMoney(total), true)

	// ── Footer ──────────────────────────────────────────────────────────
	pdf.SetY(-35)
	pdf.SetFont("Helvetica", "I", 10)
	pdf.SetTextColor(grayColor[0], grayColor[1], grayColor[2])
	pdf.CellFormat(0, 6, "Thank you for your business!", "", 0, "C", false, 0, "")

	pdf.SetY(-25)
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetTextColor(180, 180, 180)
	pdf.CellFormat(0, 4, "Generated by Invoice Maker", "", 0, "C", false, 0, "")

	// ── Watermark ───────────────────────────────────────────────────────
	pdf.SetFont("Helvetica", "B", 52)
	pdf.SetTextColor(240, 245, 255)
	pdf.SetAlpha(0.15, "Normal")
	pdf.SetXY(0, pageW+5)
	pdf.TransformBegin()
	pdf.TransformRotate(30, pageW/2, pageW/2)
	pdf.CellFormat(0, 0, "INVOICE", "", 0, "C", false, 0, "")
	pdf.TransformEnd()
	pdf.SetAlpha(1, "Normal")

	var buf bytes.Buffer
	err := pdf.Output(&buf)
	if err != nil {
		return nil, fmt.Errorf("failed to generate PDF: %w", err)
	}
	return buf.Bytes(), nil
}

func truncate(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen-3] + "..."
}

// round2 returns v rounded to 2 decimal places.
func formatMoney(v float64) string {
	v = math.Round(v*100) / 100
	s := fmt.Sprintf("%.2f", v)
	parts := strings.Split(s, ".")
	intPart := parts[0]
	decPart := parts[1]
	n := len(intPart)
	if n > 3 {
		intPart = intPart[:n-3] + "," + intPart[n-3:]
	}
	return "$" + intPart + "." + decPart
}
